name: Hello Wordl
on: push
jobs:
  say_hello:
    name: Say Hello World
    runs-on: ubuntu-18.04
    steps:
      - name: echo
        run: |
          echo 'Hello'
          echo 'World'
      - name: connect
        run: |
          echo 'connect to my repo with ${{ secrets.MY_PASSWORD }}'
  build:
    name: Build Project
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer install
        uses: php-actions/composer@v6

      - name: PhpStan
        uses: php-actions/phpstan@v3

